In [58]:
import numpy as np

In [59]:
a = np.array([(1,2,3,4,5,6,7,8),(9,10,11,12,13,14,15,16)])
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)

2
16
(2, 8)
int32


#Could be reshaped in with (1,16) (16,1) (2,8) (8,2) (4,4), (4,2,2) (2,2,4) and so on...

In [60]:
x=a.reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

<b>a[row, column]</b> for single value </br>
<b>a[from_row:to_row, from_col:to_col]</b><br>
a[:, :] all row and col

In [61]:
print(a[0,2])
print(a[0:2, 0:10])   

3
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [69]:
m = np.linspace(-1,100,10)
print(m)

[ -1.          10.22222222  21.44444444  32.66666667  43.88888889
  55.11111111  66.33333333  77.55555556  88.77777778 100.        ]
