In [1]:
import numpy as np

In [17]:
a = np.array([(1,2,4),(1,2,4)])

In [18]:
print(a.max())
print(a.min())
print(a.sum())

4
1
14


row are called axis=1 <br> col are called axis=0

In [19]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[2 4 8]
[7 7]


In [20]:
print(np.sqrt(a))

[[1.         1.41421356 2.        ]
 [1.         1.41421356 2.        ]]


In [21]:
print(np.std(a))

1.247219128924647


In [23]:
a=np.array([(1,2,3),(1,2,3)])
b = np.array([(1,2,3),(1,2,3)])

[[2 4 6]
 [2 4 6]]


In [24]:
print(a+b)

[[2 4 6]
 [2 4 6]]


In [25]:
print(a*b)

[[1 4 9]
 [1 4 9]]


In [26]:
print(a/b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
print(a-b)

[[0 0 0]
 [0 0 0]]


In [28]:
print(np.vstack((a,b)))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]


converting to 1D array

In [33]:
x=a.ravel()
print(x.shape)

(6,)
